stays/home/urls.py
from django.urls import path

from .views import home

app_name = 'home'
urlpatterns = [
    path('', view=home, name='home')
]

stays/presentation/urls.py
from django.urls import path

from .views import home, presentation_list

app_name = 'presentation'
urlpatterns = [
    path('', view=presentation_list, name='list'),
    path('<str:enrollment>/', view=home, name='home'),
]

stays/stays/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('presentation/', include('presentation.urls')),
]

stays/home/models.py
from django.db import models

# Create your models here.

stays/presentation/models.py
from django.db import models

from academy.models import Professor, Student
from career.models import Career
from django.utils import timezone

class Presentation(models.Model):
    #Datos del estudiante
    student = models.OneToOneField(Student, on_delete=models.CASCADE, verbose_name='Estudiante')
    address = models.CharField(max_length=250, verbose_name='Dirección', default='')
    phone = models.CharField(max_length=10, verbose_name='Teléfono', default='0000000000')
    career = models.ForeignKey(Career, on_delete=models.CASCADE, verbose_name='Carrera', null=True)
    period = models.CharField(max_length=20, verbose_name='Cuatrimestre', default='6')
    group = models.CharField(max_length=2, verbose_name='Grupo', default='A')
    nss = models.CharField(max_length=20, verbose_name='Número de Seguridad Social', default='000000000')
    payed = models.CharField(max_length=20, verbose_name='Pagado Hasta', default='6')

    #Datos del asesor interno
    internal_advisor = models.ForeignKey(Professor, on_delete=models.CASCADE, verbose_name='Asesor Interno', null=True)

    #Datos del empresa Contacto
    title_contact = models.CharField(max_length=20, verbose_name='Título', default='LIC')
    full_name_contact = models.CharField(max_length=100, verbose_name='Nombre Completo', default='')
    position_contact = models.CharField(max_length=150, verbose_name='Cargo', default='DIRECTOR')
    enterprice = models.CharField(max_length=150, verbose_name='Empresa', default='ACME AC')
    in_catalog = models.BooleanField(default=False, verbose_name='Empresa en Catálogo')

    #datos del asesor externo
    title_external = models.CharField(max_length=20, verbose_name='Título de Asesor Externo', default='LIC')
    full_name_external = models.CharField(max_length=100, verbose_name='Nombre Asesor Externo', default='')
    position_external = models.CharField(max_length=150, verbose_name='Cargo de Asesor Externo', default='DIRECTOR')

    # Datos del proyecto
    name_project = models.CharField(max_length=150, verbose_name='Nombre del Proyecto', default='')
    start_date = models.DateField(verbose_name='Fecha de Inicio', default=timezone.now)
    end_date = models.DateField(verbose_name='Fecha de Fin', default=timezone.now)
    period_stay = models.CharField(max_length=50, verbose_name='Periodo de Estancia', default='MAYO - AGOSTO')
    register_date = models.DateField(verbose_name='Fecha de Registro', default=timezone.now)
    modality = models.CharField(max_length=150, verbose_name='Modalidad', default='PRESENCIAL')
    line = models.CharField(max_length=150, verbose_name='Giro', default='EDUCACIÓN')

    def __str__(self):
        return self.student.enrollment + " " + self.student.full_name

stays/home/forms.py
from django import forms

class EnrollmentForm(forms.Form):
    enrollment = forms.CharField(max_length=12, label = 'Matrícula', min_length=10)

stays/presentation/forms.py
from django.forms import ModelForm

from academy.models import Professor

from .models import Presentation
from django import forms

from career.models import Career

class PresentationForm(ModelForm, forms.Form):
    # enrollment = forms.CharField(max_length=100, label='Matrícula')
    name_student = forms.CharField(max_length=100, label='Nombre')
    lastname_student = forms.CharField(max_length=100, label='Apellidos')
    email_student = forms.EmailField(label='Correo')
    class Meta:
        model = Presentation
        fields = ["address", "phone", "career", "period", "group", "nss", "payed", "internal_advisor",
"title_contact", "full_name_contact", "position_contact", "enterprice", "in_catalog", "title_external", "full_name_external", 
"position_external", "name_project", "start_date", "end_date", "period_stay", "register_date", "modality", "line"]
        widgets = {
            'address': forms.Textarea(attrs={'rows': 3}),
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
            'register_date': forms.DateInput(attrs={'type': 'date'}),
        }

class FilterForm(forms.Form):
    career = forms.ModelChoiceField(queryset=Career.objects.all(), label='Carrera', required=False)
    professor = forms.ModelChoiceField(queryset=Professor.objects.all(), label='Asesor Interno', required=False)

stays/home/views.py
from django.shortcuts import render, redirect

from .forms import EnrollmentForm

from django.contrib.auth.models import User
from academy.models import Student

def home(request):
    form = EnrollmentForm()

    if request.method == "POST":
        form = EnrollmentForm(request.POST)
        if form.is_valid():
            enrollment = form.cleaned_data['enrollment']
            enrollment = enrollment.upper()
            user = User.objects.filter(username=enrollment)
            if user:
                return redirect('presentation:home', enrollment=enrollment)
            else:
                user = User.objects.create_user(username=enrollment, password=enrollment)
                Student.objects.create(user=user, enrollment=enrollment)
                return redirect('presentation:home', enrollment=enrollment)

    return render(request, 'home/home.html', {"form": form})

stays/presentation/views.py
from django.shortcuts import render
from django.utils import timezone
from django.contrib import messages

from .forms import PresentationForm, FilterForm
from academy.models import Student
from .models import Presentation

def home(request, enrollment):
    student = Student.objects.get(enrollment=enrollment)
    user = student.user
    presentations = Presentation.objects.filter(student = student)
    if presentations:
        p = presentations[0]
    else:
        p = Presentation.objects.create(student = student)

    if request.method == 'POST':
        form = PresentationForm(request.POST)
        if form.is_valid():
            # Update Data User
            name_student = form.cleaned_data.get('name_student').upper()
            lastname_student = form.cleaned_data.get('lastname_student').upper()
            email_student = form.cleaned_data.get('email_student')
            user = student.user
            user.first_name = name_student
            user.last_name = lastname_student
            user.email = email_student
            user.save()
            # Update Data Presentation
            address = form.cleaned_data.get('address')
            phone = form.cleaned_data.get('phone')
            career = form.cleaned_data.get('career')
            period = form.cleaned_data.get('period')
            group = form.cleaned_data.get('group')
            nss = form.cleaned_data.get('nss')
            payed = form.cleaned_data.get('payed')
            internal_advisor = form.cleaned_data.get('internal_advisor')

            p.address = address.upper()
            p.phone = phone
            p.career = career
            p.period = period.upper()
            p.group = group.upper()
            p.nss = nss.upper()
            p.payed = payed

            # Update Data Asesor Interno
            p.internal_advisor = internal_advisor

            # Update Data Empresa y Asesor Externo

            title_contact = form.cleaned_data.get('title_contact')
            full_name_contact = form.cleaned_data.get('full_name_contact')
            position_contact = form.cleaned_data.get('position_contact')
            
            p.title_contact = title_contact.upper()
            p.full_name_contact = full_name_contact.upper()
            p.position_contact = position_contact.upper()


            enterprice = form.cleaned_data.get('enterprice')
            in_catalog = form.cleaned_data.get('in_catalog')
            title_external = form.cleaned_data.get('title_external')
            full_name_external = form.cleaned_data.get('full_name_external')
            position_external = form.cleaned_data.get('position_external')
            p.enterprice = enterprice.upper()
            p.in_catalog = in_catalog
            p.title_external = title_external.upper()
            p.full_name_external = full_name_external.upper()
            p.position_external = position_external.upper()

            name_project = form.cleaned_data.get('name_project')
            start_date = form.cleaned_data.get('start_date')
            end_date = form.cleaned_data.get('end_date')
            period_stay = form.cleaned_data.get('period_stay')
            register_date = form.cleaned_data.get('register_date')
            modality = form.cleaned_data.get('modality')
            line = form.cleaned_data.get('line')
            p.name_project = name_project.upper()
            p.start_date = start_date
            p.end_date = end_date
            p.period_stay = period_stay.upper()
            p.register_date = register_date
            p.modality = modality.upper()
            p.line = line.upper()
            p.save()
            messages.success(request, "Información Actualizada")
            return render(request, 'presentation/home.html', {'enrollment': enrollment, "form": form})

    form = PresentationForm()
    form.fields['name_student'].initial = student.user.first_name
    form.fields['lastname_student'].initial = student.user.last_name
    form.fields['email_student'].initial = student.user.email

    form.fields['address'].initial = p.address
    form.fields['phone'].initial = p.phone
    form.fields['career'].initial = p.career
    form.fields['period'].initial = p.period
    form.fields['group'].initial = p.group
    form.fields['nss'].initial = p.nss
    form.fields['payed'].initial = p.payed
    form.fields['internal_advisor'].initial = p.internal_advisor
    form.fields['title_contact'].initial = p.title_contact
    form.fields['full_name_contact'].initial = p.full_name_contact
    form.fields['position_contact'].initial = p.position_contact
    form.fields['enterprice'].initial = p.enterprice
    form.fields['in_catalog'].initial = p.in_catalog
    form.fields['title_external'].initial = p.title_external
    form.fields['full_name_external'].initial = p.full_name_external
    form.fields['position_external'].initial = p.position_external
    form.fields['name_project'].initial = p.name_project
    form.fields['start_date'].initial = p.start_date.strftime('%Y-%m-%d')
    form.fields['end_date'].initial = p.end_date.strftime('%Y-%m-%d')
    # print(p.end_date.strftime('%Y-%m-%d'))
    form.fields['period_stay'].initial = p.period_stay
    form.fields['register_date'].initial = p.register_date.strftime('%Y-%m-%d')
    form.fields['modality'].initial = p.modality
    form.fields['line'].initial = p.line

    return render(request, 'presentation/home.html', {'enrollment': enrollment, "form": form})

def presentation_list(request):
    if request.method == 'POST':
        form = FilterForm(request.POST)

        if form.is_valid():
            career = form.cleaned_data.get('career')
            professor = form.cleaned_data.get('professor')
            
            if career and professor:
                presentations = Presentation.objects.filter(internal_advisor=professor, career = career)
            elif career:
                presentations = Presentation.objects.filter(career = career)
            elif professor:
                presentations = Presentation.objects.filter(internal_advisor=professor)
            else:
                presentations = Presentation.objects.all()

            return render(request, 'presentation/list.html', {"presentations": presentations, "form": form})        

    form = FilterForm()
    presentations = Presentation.objects.all()
    return render(request, 'presentation/list.html', {"presentations": presentations, "form": form})

stays/templates/presentation/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Estadías</h1>
<h2>Solicitud Carta de Presentación - {{ enrollment }}</h2>
<div class="link">
<a href="{% url 'home:home' %}">Regresar</a>
</div>
{% if messages %}
{% for msg in messages %}
<h3 class="alert">{{ msg }}</h3>
{% endfor %}
{% endif %}
<form method="post">
    {% csrf_token %}
    <fieldset>
        <legend>Datos del estudiante</legend>
        <div>
        {{ form.name_student.label }}
        {{ form.name_student }}</div>
        <div>
        {{ form.lastname_student.label }}
        {{ form.lastname_student }}</div>
        <div>
        {{ form.email_student.label }}
        {{ form.email_student }}</div>
        <div>
        {{ form.address.label }}
        {{ form.address }}</div>
        <div>
        {{ form.phone.label }}
        {{ form.phone }}</div>
        <div>
        {{ form.nss.label }}
        {{ form.nss }}</div>
        <div>
        {{ form.career.label }}
        {{ form.career }}</div>
        <div>
        {{ form.group.label }}
        {{ form.group }}</div>
        <div>
        {{ form.period.label }}
        {{ form.period }}</div>
        <div>
        {{ form.payed.label }}
        {{ form.payed }}</div>
    </fieldset><br>
    <fieldset>
        <legend>Asesor Interno</legend>
        <div>
            {{ form.internal_advisor.label }}
            {{ form.internal_advisor }}
        </div>
    </fieldset><br>
    <fieldset>
        <legend>Dirigido a</legend>
        <div>
        {{ form.title_contact.label }}
        {{ form.title_contact }}
        </div>
        <div>
        {{ form.full_name_contact.label }}
        {{ form.full_name_contact }}
        </div>
        <div>
        {{ form.position_contact.label }}
        {{ form.position_contact }}
        </div>
        <div>
        {{ form.enterprice.label }}
        {{ form.enterprice }}
        </div>
        <div style="display: block;">
        {{ form.in_catalog.label }}
        {{ form.in_catalog }}
        </div>
    </fieldset><br>
    <fieldset>
        <legend>Asesor Externo</legend>
        <div>
        {{ form.title_external.label }}
        {{ form.title_external }}</div>
        <div>
        {{ form.full_name_external.label }}
        {{ form.full_name_external }}</div>
        <div>
        {{ form.position_external.label }}
        {{ form.position_external }}</div>
    </fieldset><br>
    <fieldset>
        <legend>Asignación de Proyecto</legend>
        <div>
            {{ form.name_project.label }}
            {{ form.name_project }}
        </div>
        <div>
        {{ form.start_date.label }}
        {{ form.start_date }}
        </div>
        <div>
            {{ form.end_date.label }}
            {{ form.end_date }}
        </div>
        <div>
            {{ form.period_stay.label }}
            {{ form.period_stay }}
        </div>
        <div>
            {{ form.register_date.label }}
            {{ form.register_date }}
        </div>
        <div>
            {{ form.modality.label }}
            {{ form.modality }}
        </div>
        <div>
            {{ form.line.label }}
            {{ form.line }}
        </div>
    </fieldset>
    <div class="bottom">
        <input type="submit" value="Guardar">
    </div>
</form>
{% endblock %}

stays/templates/presentation/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Solicitudes de Cartas de Presentación</h1>
<div>
    <form method="post">
        {% csrf_token %}
        <fieldset>
            <legend>Filtrar por:</legend>
            {{ form }}
            <div>
                <input type="submit" value="Filtrar">
            </div>
        </fieldset>
    </form>
</div>
<div class="table">
    <table>
        <thead>
            <th>Matrícula</th>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Teléfono</th>
            <th>Carrera</th>
            <th>Cuatrimestre</th>
            <th>Grupo</th>
            <th>NSS</th>
            <th>email</th>
            <th>Pagado hasta</th>
            <th>Asesor Interno</th>
            <th>Cargo Asesor Interno</th>
            <th>Nombre</th>
            <th>Cargo</th>
            <th>Empresa</th>
            <th>Empresa en Catálogo</th>
            <th>Nombre Asesor Externo</th>
            <th>Cargo Asesor Externo</th>
            <th>Nombre de Proyecto</th>
            <th>Fecha Inicio</th>
            <th>Fecha Fin</th>
            <th>Periodo Estadía</th>
            <th>Año estadía</th>
            <th>Fecha de captura</th>
            <th>Modalidad</th>
            <th>Giro</th>
        </thead>
        <tbody>
{% for p in presentations %}
<tr>
    <td><a href="{% url 'presentation:home' p.student.enrollment %}">{{ p.student.enrollment }}</a></td>
    <td>{{ p.student.full_name }}</td>
    <td>{{ p.address }}</td>
    <td>{{ p.phone }}</td>
    <td>{{ p.career }}</td>
    <td>{{ p.period }}</td>
    <td>{{ p.group }}</td>
    <td>{{ p.nss }}</td>
    <td>{{ p.student.user.email }}</td>
    <td>{{ p.payed }}</td>
    <td>{{ p.internal_advisor | upper }}</td>
    <td>{{ p.internal_advisor.position }}</td>
    <td>{{p.title_contact}} {{p.full_name_contact}}</td>
    <td>{{p.position_contact}}</td>
    <td>{{p.enterprice}}</td>
    <td>{{p.in_catalog}}</td>
    <td>{{p.title_external}} {{p.full_name_external}}</td>
    <td>{{p.position_external}}</td>
    <td>{{p.name_project}}</td>
    <td>{{p.start_date | date:"d/m/y" }}</td>
    <td>{{p.end_date | date:"d/m/y" }}</td>
    <td>2024</td>
    <td>{{p.period_stay}}</td>
    <td>{{p.register_date | date:"d/m/y" }} </td>
    <td>{{p.modality}}</td>
    <td>{{p.line}}</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
{% endblock %}